// PERSON B OWNS THIS FILE.
// Static course structure. Nothing here is computed, fetched, or generated.
//
// Every course, topic and activity is listed as ready. Only Projectile Motion
// has a real simulation behind it -- the rest open the same activity shell, so
// the navigation reads as a finished product without anything dead-ending or
// throwing. If you demo a branch other than Physics > Kinematics, say so.
//
// Physics constants and equations are NOT here -- they come from contract.js via
// equation.js. Never restate a constant in a content file.

// Screen 4 renders these for every activity, so every subtopic must carry them
// or Launch.jsx throws on .map(). Projectile Motion overrides them with its own.
const GENERIC_BRIEF = {
  objective:
    'Work out the quantity this activity asks for, then run the simulation with your own value and watch what it does.',
  prereqs: [
    'Rearranging an equation to isolate one variable',
    'Substituting given values and keeping the units straight',
    'Reading a result off a graph or a simulation',
  ],
  studentSteps: [
    'Read the scenario and the values you are given.',
    'Solve for the quantity the activity asks for.',
    'Run the simulation with your number.',
    'If it misses, work out which part of your reasoning was wrong.',
  ],
  available: true,
};

export const COURSES = [
  {
    id: "physics",
    name: "Physics",
    grade: "Grade 11",
    section: "Section B",
    students: 32,
    teacher: "Harshita Jogi",
    band: "#4338ca",
    description: "Motion, forces, and energy.",
    topicCount: 5,
    progress: "2 of 5 topics started",
    available: true,
  },
  {
    id: "maths",
    name: "Mathematics",
    grade: "Grade 11",
    section: "Section B",
    students: 32,
    teacher: "Harshita Jogi",
    band: "#0f766e",
    description: "Functions, trigonometry, and rates of change.",
    topicCount: 6,
    progress: "1 of 6 topics started",
    available: true,
  },
  {
    id: "chemistry",
    name: "Chemistry",
    grade: "Grade 11",
    section: "Section A",
    students: 29,
    teacher: "Harshita Jogi",
    band: "#b45309",
    description: "Reactions, moles, and equilibrium.",
    topicCount: 5,
    progress: "1 of 5 topics started",
    available: true,
  },
  {
    id: "biology",
    name: "Biology",
    grade: "Grade 11",
    section: "Section A",
    students: 29,
    teacher: "Harshita Jogi",
    band: "#9d174d",
    description: "Genetics, cells, and inheritance.",
    topicCount: 4,
    progress: "1 of 4 topics started",
    available: true,
  },
];

// keyed by course id
export const TOPICS = {
  physics: [
    {
      id: "kinematics",
      name: "Kinematics",
      description: "How things move, before asking why.",
      icon: "📐",
      subtopicCount: 4,
      meta: "4 activities",
      available: true,
    },
    {
      id: "forces",
      name: "Forces and Motion",
      description: "Newton's laws, friction, and free-body diagrams.",
      icon: "🧲",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "energy",
      name: "Energy",
      description: "Work, power, and conservation.",
      icon: "⚡",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "waves",
      name: "Waves",
      description: "Oscillation, frequency, and interference.",
      icon: "🌊",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "circuits",
      name: "Electricity and Circuits",
      description: "Current, resistance, and series versus parallel.",
      icon: "🔌",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
  ],
  maths: [
    {
      id: "functions",
      name: "Functions",
      description: "Mapping inputs to outputs, and reading the shape.",
      icon: "📈",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "trig",
      name: "Trigonometry",
      description: "Ratios, identities, and solving triangles.",
      icon: "📐",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "sequences",
      name: "Sequences and Series",
      description: "Patterns that continue, and what they sum to.",
      icon: "🔢",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "calculus",
      name: "Rates of Change",
      description: "Gradients, derivatives, and tangents.",
      icon: "📉",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "probability",
      name: "Probability",
      description: "Counting outcomes and weighing chance.",
      icon: "🎲",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "vectors",
      name: "Vectors",
      description: "Quantities that carry a direction.",
      icon: "➡️",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
  ],
  chemistry: [
    {
      id: "atomic",
      name: "Atomic Structure",
      description: "Shells, isotopes, and why atoms behave as they do.",
      icon: "⚛️",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "bonding",
      name: "Bonding",
      description: "What holds atoms together, and the shapes that result.",
      icon: "🔗",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "moles",
      name: "Moles and Stoichiometry",
      description: "Counting particles by weighing them.",
      icon: "⚖️",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "equilibrium",
      name: "Reactions and Equilibrium",
      description: "Rates, reversibility, and shifting a balance.",
      icon: "🧪",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "organic",
      name: "Organic Chemistry",
      description: "Carbon chains and the groups hung off them.",
      icon: "🛢️",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
  ],
  biology: [
    {
      id: "cells",
      name: "Cells",
      description: "The unit everything living is built from.",
      icon: "🔬",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "genetics",
      name: "Genetics",
      description: "How instructions are stored and read.",
      icon: "🧬",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "inheritance",
      name: "Inheritance",
      description: "Passing traits on, and predicting the odds.",
      icon: "👪",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
    {
      id: "ecology",
      name: "Ecology",
      description: "Populations, energy flow, and cycles.",
      icon: "🌱",
      subtopicCount: 3,
      meta: "3 activities",
      available: true,
    },
  ],
};

// keyed by topic id
export const SUBTOPICS = {
  kinematics: [
    {
      id: 'projectile',
      name: 'Projectile Motion',
      icon: '🏀',
      blurb: 'Work out how fast to throw, then watch it happen.',
      objective:
        'Solve for the launch speed that puts a ball through a hoop, given a fixed launch angle and a release point above the ground.',
      prereqs: [
        'Splitting a velocity into horizontal and vertical components',
        'Reading sine, cosine, and tangent of a given angle',
        'Rearranging an equation with a squared term',
      ],
      studentSteps: [
        'Solve for the launch speed and enter it.',
        'Shoot — the ball flies with your number.',
        'Read what the court did, not whether you were marked right.',
        'If it missed, work out which part of your reasoning was wrong.',
      ],
      estTime: '10 min',
      available: true,
    },
    {
      ...GENERIC_BRIEF,
      id: "speed",
      name: "Speed and Velocity",
      icon: "🚗",
      blurb: "Distance over time, and why direction matters.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "accel",
      name: "Acceleration",
      icon: "📈",
      blurb: "How quickly velocity itself changes.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "dtgraph",
      name: "Distance–Time Graphs",
      icon: "📊",
      blurb: "Reading motion off a gradient.",
      estTime: "8 min",
    },
  ],
  forces: [
    {
      ...GENERIC_BRIEF,
      id: "newton2",
      name: "Newton's Second Law",
      icon: "⚖️",
      blurb: "Force, mass, and the acceleration that follows.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "friction",
      name: "Friction",
      icon: "🛞",
      blurb: "The force that argues with every motion.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "freebody",
      name: "Free-Body Diagrams",
      icon: "🧭",
      blurb: "Drawing every force acting on one object.",
      estTime: "8 min",
    },
  ],
  energy: [
    {
      ...GENERIC_BRIEF,
      id: "work",
      name: "Work and Power",
      icon: "🏋️",
      blurb: "Force through a distance, and how fast you do it.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "kinetic",
      name: "Kinetic Energy",
      icon: "🎢",
      blurb: "The energy a moving mass carries.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "conservation",
      name: "Conservation of Energy",
      icon: "♻️",
      blurb: "Energy changes form but never vanishes.",
      estTime: "10 min",
    },
  ],
  waves: [
    {
      ...GENERIC_BRIEF,
      id: "wavespeed",
      name: "Wave Speed",
      icon: "🌀",
      blurb: "Frequency times wavelength, and what that means.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "interference",
      name: "Interference",
      icon: "〰️",
      blurb: "Two waves meeting, adding and cancelling.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "doppler",
      name: "The Doppler Effect",
      icon: "🚨",
      blurb: "Why a siren changes pitch as it passes.",
      estTime: "9 min",
    },
  ],
  circuits: [
    {
      ...GENERIC_BRIEF,
      id: "ohms",
      name: "Ohm's Law",
      icon: "💡",
      blurb: "Voltage, current, and resistance in one relation.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "series",
      name: "Series and Parallel",
      icon: "🔋",
      blurb: "How arrangement changes what a circuit does.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "elecpower",
      name: "Electrical Power",
      icon: "⚙️",
      blurb: "Turning current and voltage into watts.",
      estTime: "9 min",
    },
  ],
  functions: [
    {
      ...GENERIC_BRIEF,
      id: "domain",
      name: "Domain and Range",
      icon: "🎯",
      blurb: "Which inputs are allowed, and what comes out.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "graphs",
      name: "Graphing Functions",
      icon: "📉",
      blurb: "Turning a rule into a picture.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "inverse",
      name: "Inverse Functions",
      icon: "🔄",
      blurb: "Running a function backwards.",
      estTime: "9 min",
    },
  ],
  trig: [
    {
      ...GENERIC_BRIEF,
      id: "ratios",
      name: "Sine, Cosine, Tangent",
      icon: "📐",
      blurb: "The three ratios that unlock a triangle.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "identities",
      name: "Trigonometric Identities",
      icon: "🔁",
      blurb: "Relations that hold for every angle.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "sinerule",
      name: "Sine and Cosine Rules",
      icon: "🔺",
      blurb: "Solving triangles that are not right-angled.",
      estTime: "10 min",
    },
  ],
  sequences: [
    {
      ...GENERIC_BRIEF,
      id: "arithmetic",
      name: "Arithmetic Sequences",
      icon: "➕",
      blurb: "A constant step, every term.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "geometric",
      name: "Geometric Sequences",
      icon: "✖️",
      blurb: "A constant ratio, every term.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "sums",
      name: "Series and Sums",
      icon: "∑",
      blurb: "Adding a sequence without adding every term.",
      estTime: "9 min",
    },
  ],
  calculus: [
    {
      ...GENERIC_BRIEF,
      id: "gradient",
      name: "Gradient of a Curve",
      icon: "📐",
      blurb: "Slope at a point, not across an interval.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "differentiation",
      name: "Differentiation",
      icon: "📉",
      blurb: "Finding the rate of change as a rule.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "tangents",
      name: "Tangents and Normals",
      icon: "📏",
      blurb: "Lines that touch a curve exactly once.",
      estTime: "9 min",
    },
  ],
  probability: [
    {
      ...GENERIC_BRIEF,
      id: "outcomes",
      name: "Counting Outcomes",
      icon: "🎲",
      blurb: "Listing what can happen, without missing any.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "conditional",
      name: "Conditional Probability",
      icon: "🔀",
      blurb: "Chance once you already know something.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "distributions",
      name: "Distributions",
      icon: "📊",
      blurb: "Spreading probability across outcomes.",
      estTime: "10 min",
    },
  ],
  vectors: [
    {
      ...GENERIC_BRIEF,
      id: "components",
      name: "Resolving Vectors",
      icon: "🧭",
      blurb: "Splitting a vector into perpendicular parts.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "magnitude",
      name: "Magnitude and Direction",
      icon: "📏",
      blurb: "Size and heading from components.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "addition",
      name: "Adding Vectors",
      icon: "➕",
      blurb: "Combining two directions into one.",
      estTime: "9 min",
    },
  ],
  atomic: [
    {
      ...GENERIC_BRIEF,
      id: "shells",
      name: "Electron Shells",
      icon: "🔆",
      blurb: "Where electrons sit, and why it matters.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "isotopes",
      name: "Isotopes",
      icon: "🧊",
      blurb: "Same element, different mass.",
      estTime: "8 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "ions",
      name: "Ions",
      icon: "⚡",
      blurb: "Atoms that have gained or lost charge.",
      estTime: "8 min",
    },
  ],
  bonding: [
    {
      ...GENERIC_BRIEF,
      id: "ionic",
      name: "Ionic Bonding",
      icon: "🧂",
      blurb: "Transferring electrons and holding on.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "covalent",
      name: "Covalent Bonding",
      icon: "🔗",
      blurb: "Sharing electrons between atoms.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "shapes",
      name: "Molecular Shapes",
      icon: "🔷",
      blurb: "Why molecules bend the way they do.",
      estTime: "10 min",
    },
  ],
  moles: [
    {
      ...GENERIC_BRIEF,
      id: "molarmass",
      name: "Molar Mass",
      icon: "⚖️",
      blurb: "Weighing a mole of anything.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "balancing",
      name: "Balancing Equations",
      icon: "🟰",
      blurb: "Conserving atoms across a reaction.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "yields",
      name: "Reacting Masses and Yield",
      icon: "📦",
      blurb: "Predicting how much you actually get.",
      estTime: "10 min",
    },
  ],
  equilibrium: [
    {
      ...GENERIC_BRIEF,
      id: "rates",
      name: "Rates of Reaction",
      icon: "⏱️",
      blurb: "What speeds a reaction up, and why.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "reversible",
      name: "Reversible Reactions",
      icon: "🔁",
      blurb: "Reactions that run both ways at once.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "lechatelier",
      name: "Le Chatelier's Principle",
      icon: "⚖️",
      blurb: "Pushing a balance and watching it shift.",
      estTime: "10 min",
    },
  ],
  organic: [
    {
      ...GENERIC_BRIEF,
      id: "alkanes",
      name: "Alkanes and Alkenes",
      icon: "🛢️",
      blurb: "Saturated chains, and the ones with a double bond.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "functional",
      name: "Functional Groups",
      icon: "🔬",
      blurb: "The handles that decide how a molecule reacts.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "isomers",
      name: "Isomers",
      icon: "🪞",
      blurb: "Same formula, different arrangement.",
      estTime: "9 min",
    },
  ],
  cells: [
    {
      ...GENERIC_BRIEF,
      id: "structure",
      name: "Cell Structure",
      icon: "🔬",
      blurb: "Organelles and what each one does.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "transport",
      name: "Transport Across Membranes",
      icon: "🚪",
      blurb: "Diffusion, osmosis, and active transport.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "division",
      name: "Cell Division",
      icon: "➗",
      blurb: "Mitosis, meiosis, and why both exist.",
      estTime: "10 min",
    },
  ],
  genetics: [
    {
      ...GENERIC_BRIEF,
      id: "dna",
      name: "DNA Structure",
      icon: "🧬",
      blurb: "The double helix and how it stores information.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "protein",
      name: "Protein Synthesis",
      icon: "🏭",
      blurb: "Reading a gene and building a protein.",
      estTime: "10 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "mutation",
      name: "Mutations",
      icon: "🎲",
      blurb: "Changes in the code, and their consequences.",
      estTime: "9 min",
    },
  ],
  inheritance: [
    {
      ...GENERIC_BRIEF,
      id: "punnett",
      name: "Punnett Squares",
      icon: "🔲",
      blurb: "Predicting the odds for offspring.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "alleles",
      name: "Alleles and Dominance",
      icon: "🅰️",
      blurb: "Why some traits mask others.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "pedigrees",
      name: "Pedigree Charts",
      icon: "🌳",
      blurb: "Tracing a trait through a family.",
      estTime: "9 min",
    },
  ],
  ecology: [
    {
      ...GENERIC_BRIEF,
      id: "foodwebs",
      name: "Food Webs",
      icon: "🕸️",
      blurb: "Who eats whom, and where energy goes.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "cycles",
      name: "Nutrient Cycles",
      icon: "🔄",
      blurb: "Carbon and nitrogen going round.",
      estTime: "9 min",
    },
    {
      ...GENERIC_BRIEF,
      id: "populations",
      name: "Population Dynamics",
      icon: "📈",
      blurb: "What makes a population grow or crash.",
      estTime: "10 min",
    },
  ],
};

export const findCourse = (id) => COURSES.find((c) => c.id === id);
export const findTopic = (courseId, id) =>
  (TOPICS[courseId] || []).find((t) => t.id === id);
export const findSubtopic = (topicId, id) =>
  (SUBTOPICS[topicId] || []).find((s) => s.id === id);
